local b64chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local b64invchars = {}
for i = 1, #b64chars do
    b64invchars[b64chars:sub(i,i)] = i - 1
end

local function base64_decode(data)
    data = data:gsub("[^"..b64chars.."=]", "") -- Remove invalid characters
    local result = ""
    local padding = data:match("(=*)$") or ""
    data = data:gsub("=+$", "") -- Remove padding for decoding
    local len = #data

    for i = 1, len, 4 do
        local c1 = b64invchars[data:sub(i,i)]
        local c2 = b64invchars[data:sub(i+1,i+1)]
        local c3 = b64invchars[data:sub(i+2,i+2)]
        local c4 = b64invchars[data:sub(i+3,i+3)]

        local n = (c1 << 18) + (c2 << 12) + (c3 << 6) + c4

        local byte1 = (n >> 16) & 0xFF
        local byte2 = (n >> 8) & 0xFF
        local byte3 = n & 0xFF

        result = result .. string.char(byte1)
        if c3 ~= nil then result = result .. string.char(byte2) end
        if c4 ~= nil then result = result .. string.char(byte3) end
    end
    -- Handle padding
    if padding == "=" then
        return result:sub(1, #result - 2)
    elseif padding == "==" then
        return result:sub(1, #result - 1)
    end
    return result
end
-- --- End Base64 Decoding Function ---

-- --- Main Script Logic ---

-- 1. PASTE YOUR BASE64 STRING HERE
-- IMPORTANT: Replace "YOUR_BASE64_STRING_GOES_HERE" with the actual Base64 data
-- from your input.txt file. If it's very long, you might need to split it
-- into multiple lines or chunk it, though a single long string is often fine.
local base64Data = "LFW1rLK00lLTSq2qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzUtFKrKq1UtdSqqqqqKq1UtdJS00qtqqqqqqqqqkorTStVS1O10rIqVS0rVa3UqtRKUyutSi0rtbLSslKrqqqqqqqqqqq0UtUqtarUUitTq1LLSstSK0utyjTT1Cq1KrUs1VIzVSs1K1UrVdOy1MpKrSwrLVVVVVVVVVVVLcssy7KqKitVVdWyyqwsq6rKrMqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqLNVUVVVVVVVVNUtVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTU1y1TNqlRVVdWsLK2yqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoqU1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTVdWqyqzKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdWsTFVVs6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0kq1LFVVVVVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTVWrrKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiorqypTVVVVM1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTVVVVVVVVVVVVVTTVW1UtWqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsqqqqqqqqqqqqqosU1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVNdWqVK2ssqqqKq2qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKquqqqqqqqqqqkxVVVVVVUutyjLN1FRVVdVUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1co0VVVVVbVKq6qqrKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiqzqqqqqqqqqqqqqqqqsrKsqqyqqqqqKlXVNE0rVVVVVVVVVVVV1VRVVVVVVVVVVVVVVVVVNc0qVVVVVVVVVVVVVVWzqqqqqqpK1ayqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtKqqlRVq6qqqqqqKi1VVVVVVVVVVVVVVVVVVdWqqqqqqkpVVVVVVVVVraqqqiqzqqyqqqpUVVVVVVVVVVW1qqqqqqqqqqqqqkpVVVVVVVVVVdWqqqqqqqqqqqqqqlRVVVVVVVVVVVVVraqqqqqqqqqqqqqqqqpSValKVamqSrWq1dbatra1WlWpUqmUSkqSJIlECEIkqba7+717u9fdNpWUSlWVKkkihEBCIVEqVZWqtW2r9Xt313uvbaVSqZSSJEkkhCAikqSqlFJSa7vd2vve2+u9WqWkkpKkpCSSREQiKVWlqqpSlVbVau373rvtbatKRKCk2mpCkCARSqpUVUslUdXa2mrb/X53d71VBIqgUmstSQREFCJJrVZTSaRSta223d/3vnfXJEFElMpWKxECBZEobdtqhCBEFElt+/f/7/u2JhGEEKlUbavtunvrlhAgIERSldvX/v//f7eVIkAQIpJSW/f3991KghAQiShJqdr9//+/W5WIQCBERKl2/793V4kQiIgkkSS19t7//W9bJYQIiAiSav//77UqQghBRChVrVvrtv73L6pAQkqAEOp+/9/eUiUIAIRa1qoq3aoX+O9/2pASVQCC6Pv9b+2WIgIAonrNqlJ2QSrw//9RE00qAUjS/927tltAAKCydquqlVgByND//0dNqiABUPX/XXtXKwAQ1LZqN+0iEERU1f//n1RIQgLQ2v/fupUqAIjU7qqvqgSARFVJ//9/SIQiEqC7/29VF0kApOrdVW0lBUBItWrp//8HJFBCCfr7f6tUCQkg1ffeVBUVEEKZ1mrt//8DEJSkQn7/3ypUQQqo2t9bUUUpCJHKaqu7//8HQKCkkvT//6pEghShav+7hSSkIkmRqvp62///AQBU0UK//99KkKAKaup/b0QCLakkkmptq/X//wAEqNSkr/+/RRBIJVX1369EQEpVSYJqu2vt//8ABFCyqd3+/yYQoIpa1W9/SQEStZIKqurX3f//BQQgUSu7/v9dQgBKtGW3/moJhFCVKqLKfbf97y8QAIWq2tv/30UEIEmrbr3rlkgAklSlUu3+t//1AwqAIDfb7e9vSQEI0mp329YlFYAIValV2377f/+ABCChVr3992+lAAioat92a0tFgEBSqrW2vb3/9QcUgAitur2/f7UBBKCSve22VlWEAEiSVavd9u3/foEKQKBVbvvbv92AAlChV+/aVU1QAArSUpfe7Kv/9kMlgBAtdeve390SBUBB1vKubVUSAQgkSatd/e77//1FBVAgTdq1ffe+UgVAQEvu2tYrnYAEKFErW/Wnf/7vL2lACqiSbdW/39dagIJooS7tVt0KJYBCStrVrva+/+8/tUAJVIla0W//224oCaigFtSV9qUukIRUVlUlPfWv//1XO6ECKpFKab/+y16ogzqkAkkqbaqqaqtbbUlNVJXd9X9/VxtUCSmgEFJrf92XrKIKIZBQIq1aU7Vtb2vZsKFiqav//V5bIlVQAgmiVNutK6tmrSQEQkGlqlVb3d29aXLItLSqtv29u7pJqaREEBIRqaZaabVaKQkhRCRptdquu1otrVWtVJVVq7VqbW2tSlWlqZSSlKpSqZQqValUSlWr1aqqqlZrVaWpVSurqmq1qqqqWq1atapVU1WlSpVKpVKllEqVqqq0rKpqVdWqWlVVq6qqstTSsqqqVVWrqmpVVVW1qqqqqkpVVZWqUlWqVFWpqqqqalVVtaqqqqqqqqqqSlVVVdWqqqqqqlZVVVVV1aqqqqoqVVVVVVVVVZWqqqqqalVVVVVVVVWqqqqqqqqqqqqqqqpqVVVVVVVVVVVVVaWqqqqqqqqqqlZVVVVVVVVVVVVVVpqqqqqqqqqlqlVVlVVVVVVVVVVVVaWqqqqqqqpVVVVVVVVVVVVVVaqqqqqqqqqqqqqqqlqpqqqpqqqqqqqqqqqqqqqqqqqqqqqqaqqqqqqqqqqqqqqqqlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVaqqqqqqqqqqqqqqqqqqVVVVlZWqqqqqlqaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqamaqqqlaVWlVVVVVVZVWVaZWaWVWpqpVWlZpVqapqqllTVd0/AMj+FVD9VwK194qicmcCI6v/vwCobklQ+62Q+W2JUG2XgeT2iaD/K4HqzoBIe1dK2m9FqPY1hOouBqFeVlrZ+bWi5KoJhGqbqNS1zczWqxORJkuSLFtLTeu2KjKrKZG0myKpu6uSut0KaN0loOzXBOp9DaF9TRBq3wJJuyaidhVJ1Fqp3bVVqasUVdWuUu/XRszehRBVTUJU22ZSraoEoqqSNNst1dr7Fcmsthnzfn2VmSOCIqRW7Gq1U2IllYJAIZRIcp9rK3tXJWbtndu9Pyu1UhSQyjrWzf02kUqqAkpJERGZW5mJ7M7Iitpbe7fzd9avbmNkBkWMsFZ17ZlNEUtlRqpqq0xEIkSQRLTkztyuazvndru3+zc3I0YFKaL6Zlk3uyEwU1clujebIFSJEECtqS3JfatdyTtxlvvX/duqQISEiFnfu+pMJQBEqr7b/vbWAiASFUTqfW0lpMrUzOxW7/a3b/9uZQAlkojq/91mqisAIFL32vrebgKEiCSR1Ou3QqmkVFXtrLs393dvf1UFACFEUnX/3a2qCEBE1O7uu/WXRICIpEiq+15bkYjJzdbW7t5t7/19WwUgFFEi0vu7q5WSgBBSdt/eXd9WCAhCJFVtd79VFVlVi2zrfdndv723KgASkhKSvHdvq5RESBCUar/Xfa1MIEiIhCLV7e6qVa2qpdq1d7vW9u5vWwIFRRJJUu3eXVWpVFVKSVW1rVqVqpIkJFIqlapa26pVVa1VZbXdtqpV262tVEmtqkqVVJUqpVSSUqmqUlXV2mpVtVVTVaqqUkmUVKUIqaxVk1Z1u2vb9u7ed6/7bteKSCIJQkIoRCilVFWtrW3btq21rVoqkYhEBEEoQiLJ1nb73t29vXd3r7t3a4VQUCIQIgoSIYlUbevu7vZua6uWUiIEIhJEggQlKdt2X3+3d+/e2+7ebSshKCQIERIhoSKlbbfdd2/fXne3JVECQSREhCgkSW3bd/3d3X777q7u3a0IohBBCJGEkIiUWtt2v7t73b27JSIhBCEiChSiJLXtvf5ub9/bd9f27rYSRBFBEBIJChFJqrXt7nvdrrValSJCECRCFEgkSda2r/u9vdt377bbvW0VQhEhiAgJhRBJ0qrV7u7a1tZqlaRIEggKCgohktS2bb3v7l7vvbvd7t5uRSISSSAiESEUkVZVVevaVquqalWSpJIkkkilSkm17Xate9/rve7Xt21rq5UokqQkQiSlRElVqqoqbVVVVaVqKkmlUkopqaoqVa2t27bu7ba7dp27u7lVS1VSSkqSJKUoKVUqpVJVlcpUqqqqVKqlKlVpVZWqtapWa9vaarvuWqvadquUta2UlFJlSpKoKiVJKlUpqVJVqVRVVaqqSlVVVVWrqrVq1bbWWlvbVq3WWq2sal2VUlZVJZVkqkqkSqUolVKpUqpUValSrVRVNauqVau1Vq22tVZVq62pqraqVVW1VltTVVZVSkqlUkpSSilVKqVUVaVKVVVVqqpqValqVatarbVWW2ttVduqlbJVtaQ1talWsqWaqEot0hIt0QpVUZVSVZWqSi1VVa3Uqlpp1WpVa9Wy2tpaVbW1KlW1aiVVq1ZVlaqaShWtkpZoRWlSSaVapSrZSi1VVa1aVVVVpa1slbVqq6pqqy1pq1alSqtWparaJVXUVqqkqqqUSlVJlaqVqlRLVVVVlapWTVVVraqqWm1VrVpVVeqqqqpVVVVVVWpVtbKqVJVSVVWpVqkqVVWVqlpVlapUVWpVlWpVlapqVVW1WlWqVbXSqqqlVWpVVVXV0ipVU7VUTVWVVZWmqqrUUq2yVFUtVVVVVVVZVVVVVVVVVVVVVVWqqlZZVVVVVbXSKq2qqqqqqlRVK61ULatSq6qqqqqqqmqqqqqqSlXVUlVVVVVVVauyqqpSVVVVVStVVVVVVVVVVVWtUtOqqqqqqipVq1JVVVVVVa2yqqqqqqqqqqqsUlVVVVVVVVW1qqqqqqqqtKpKVVVVVVVVVbWqqqqqqqqqqtRUVVVVVVVVVbWqqqqqqqqqqqpKVVVVVVVVVVWrqqrSUqtSK1VVVVVVVU1VrapSVauqqqqqStWqqqqqqipVVVVVVVVVVVWtqqqqqqqqqqqqVFVVVVVV1aqqqqqqqqqqqqpSVVVVVVVVVdWqqqqqqipVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVa2qqqqqqqqqqqqqTLOqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKquqqiw1q6qqqrKqqsrSVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdW0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqTDWrsqoyLbVKVVVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXNSlVVVTXNrCqrqsq0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKrNMU1VNVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVNVVVq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyqjI1VVVV1VTVUlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVW1qqqqqqqqqtK0qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrKqqqqqqqqtDJNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVc1UVVVV1aqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsqqqsqqqqqqpUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXVVDWrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKlOrqiqrqqqqKlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU9WqqjSrqrJU1TSrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKlVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVzVJLLVOzqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrKqqsqpSqzJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXVVFVVVVXVssqqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpSVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVtarUqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqUs2qqrRStVJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVM61U1aqqqrIqtaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXTTK2qLKuqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiq1KktVy1JVVVNLVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV0zTVsqyqTLNUK6uqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyqpKtcqqqlJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVNtcpK1Sq1qjSrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKquqqqqqSlNVVbNK01RVVVVVVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUtq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtKsyiyrqqpKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWrzKqqqqyqqqrUqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsUtWsUtW0qqoqVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU1VVNVy6yqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoqy6yqqqpUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVavKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsqqqqqqqqqoqqypTVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdVMNcuqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqSlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXNsqqsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKssqVbWqNDNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdVUVVXVqqoqVa2qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoqK7OqsqqqSquyqqoqVbNKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVNVVVVVVW1KquqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrMzCxVU1U1K8tUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVa3SqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrEqtVM1SVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVc2qyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqUtVUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdUsVa2qrKyqqtLUqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKrWqqqqqqqqqqqqqtKxUVVVVq1RVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXVSk1VM1WrqlKtqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVtaqqqqqqqqqqqqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoqtaqqqqpKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVtaoqU9XKrKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyqqqqqqpMTVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVXVLKuqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKquqqqqqqqqqqlJVVatSq1StVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU2rqiqrsiqrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqjK1qqoyVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1apKq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqysSqtUTVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVW1VK2qqkpVy6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqio1K1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU1VVVVVVVVVauqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqUlXVUlNNVdVUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU1VVVVVbXUqqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqoq1VRNVU1VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdVKVTVLq7KsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqipTVVVVVVXVVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUtq6qqsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqSq1KTVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTWrqqyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrKqqqqqqqqTFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKzVV1UzVsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqslRVtVJVVVVVVVVVVVVVVVVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVLTPVqqqqqqrKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiqrqqrKKlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1VRVy6qqqkqrqqqqrKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqVFWtqqqqrMpMVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVavSVFVVVa1Ks6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqNKuqqqpUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVNcusqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqNE1VVU2t1EpVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1azUskxT1UrVqrKsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrKqjJTtdKqVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVT1bSqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtFRV1cpSVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVdVUraxKNauqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpSqyrTrLRSVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1aqsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqySlUtVU1NVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTOrqlK1SquqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrUqsrUVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU1s6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrKNKtSVbWyKlVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV1VJVVdNUzaqyVFXTqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrKqqpUVVVVVTWr1FRVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUzVa20UtO0StWqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsysSk1VtcyySlVVVVVVVVXVTFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVK7WqqqqqqqpSVVM1q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkpVM6sqq1KtylRVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVNVOzqizVVK3MsjSrqqoqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqio1tcoqVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVT1VRNzbSqzKqqqqpMraqqqjLTqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKquqqqqqsipTrVLL0lRVVVVVVVNVVVVVVVVVVVVVVVVVVVVVVVVVVVVNVTVVLU1Trcw0S1WtNKuqqqqqSs0yq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqKquqrKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrJUVVVVVVVVKy21LLUqtUotVa0stbKqqqrUslLLqqrKSk1LraqqqtTKUisrrSy1sqoqKzWt1FLLSi0rLSu1qqqqqiorNa3Uqqqy1LJSq6q0slS1rFLVSq1KrSyttKqqqiqtVLVSSytVrdSqqqqqSi1VrdSqqqqqKrVUtVKrqqqqqqqqqqqqqqo=" -- <--- PASTE YOUR BASE64 DATA HERE!

-- 2. Find the speaker peripheral
local speaker = peripheral.find("speaker")
if not speaker then
    print("Error: No speaker found! Make sure it's placed next to the computer/turtle.")
    return
end

-- 3. Define the output file path for the decoded DFPWM
local decodedDfPwmFile = "embedded_audio.dfpwm" -- Name for the temporary decoded file

if #base64Data == 0 or base64Data == "YOUR_BASE64_STRING_GOES_HERE" then
    print("Error: Base64 data is missing or not pasted into the script.")
    print("Please edit this script and paste your Base64 string into the 'base64Data' variable.")
    return
end

-- 4. Decode the Base64 string to binary DFPWM data
print("Decoding Base64 data...")
local dfpwmBinaryData = base64_decode(base64Data)

if not dfpwmBinaryData or #dfpwmBinaryData == 0 then
    print("Error: Failed to decode Base64 data or decoded data is empty.")
    return
end

-- 5. Save the decoded binary data to a new .dfpwm file
print("Saving decoded DFPWM data to " .. decodedDfPwmFile .. "...")
local outFileHandle, err = fs.open(decodedDfPwmFile, "wb") -- Open in binary write mode
if not outFileHandle then
    print("Error opening " .. decodedDfPwmFile .. " for writing: " .. err)
    return
end
outFileHandle.write(dfpwmBinaryData)
outFileHandle.close()
print("DFPWM file created successfully.")

-- 6. Play the DFPWM audio
print("Playing " .. decodedDfPwmFile .. "...")

local dfpwm = require("cc.audio.dfpwm")
local decoder = dfpwm.make_decoder()
local audioFileHandle, err = fs.open(decodedDfPwmFile, "rb") -- Open in binary read mode
if not audioFileHandle then
    print("Error opening " .. decodedDfPwmFile .. " for playback: " .. err)
    return
end

local chunkSize = 16 * 1024 -- 16KB per chunk, optimal for DFPWM streaming

while true do
    local chunk = audioFileHandle.read(chunkSize)
    if not chunk then
        break -- End of file
    end

    local buffer = decoder(chunk)
    while not speaker.playAudio(buffer) do
        -- Speaker buffer is full, wait for it to empty
        os.pullEvent("speaker_audio_empty")
    end
end

audioFileHandle.close()
print("Finished playing audio.")